### ISSUE TITLE
2.0.1 Missing features and not working on Safari

### ISSUE THREAD

**Issue by bartoszhernas** [layerhq/layer-websdk#104]
Hi guys,

I have tried to update to the latest package: 2.0.1.

First, it doesn't work on Safari at all:

[https://www.dropbox.com/s/9sna4wzm5bmfidg/Screenshot%202016-09-03%2016.59.06.png?dl=0](https://www.dropbox.com/s/9sna4wzm5bmfidg/Screenshot%202016-09-03%2016.59.06.png?dl=0)

Second, it doesn't return anymore `image/png+preview`, same for videos and also JSON sizes

**Comment by michaelkantor** [comment]
This site had an interesting hint: http://stackoverflow.com/questions/26268761/websocket-url-is-deprecated-please-use-websocket-url-instead; See, your error message suggests that Layer is iterating over and accessing every single property of the WebSocket object which I don't think we ever actually do.    See if you can enable `break on error` in your debugger and find which line is actually triggering all of these errors.

Michael

**Comment by bartoszhernas** [comment]
I checked closely and it is failing when `LayerEvent` object is created:
https://www.dropbox.com/s/0nsbbdzwzqk0gy6/Screenshot%202016-09-05%2012.04.13.png?dl=0

Could you also tell me what happened with previews of rich content?
I have just realized that they stopped being delivered in old version as well which is really bad for us as we had been depending on this.

**Comment by michaelkantor** [comment]
I'm not aware of any changes to previews of rich content; however, if you see the Changelogs for the 2.0.0 release, you'll see that there have been some changes to how this content is delivered (no more base64 encoding; only Blobs, strings or null if the data needs to be loaded).

If you want to share a URL and credentials that would replicate the reported problem, i can investigate further tomorrow.

**Comment by bartoszhernas** [comment]
Yes, I am aware of changes, I have adopted the `blob` response to be displayed properly.

Ok, I have found the issue: the iOS SDK when sending attachments is sending additional data like `application/json+imageSize` and `image/jpeg+preview`. Issue is (and was) that it is created by the client, so when I started testing this and using data sent from web SDKs, I was missing this features.

I guess I have to reimplement this in JS then or say goodbye ;)

Still, I have no idea why the newest web-sdk is failing on safari. I will see if this is webpack issue (by testing with CDN)

**Comment by michaelkantor** [comment]
1. That json+imageSize data is not new; so there _should_ be no changes to your app from this.  If there are, lets see if we can better understand it.
2. https://github.com/layerhq/layer-websdk/blob/1.1.0/src/message-part.js#L632 shows that "application/json+imageSize" should be treated as textual data (delivering it as a blob could certainly have broken an app)
3. I'm not familiar enough with webpack to comment on it, but I'd be inclined to better understand who or what is accessing websocket.URL.  If your feeling up to a challenge, you can try and overwrite `client.socketManager._socket` with an object that exposes a lot of stub methods, and define a property getter/setter for URL that you can put a breakpoint into.

**Comment by bartoszhernas** [comment]
I am sorry, it works on Safari (something else was breaking the build). I am still getting errors about deprecation but chat works just fine. 

1. Yes, what I meant is that when I started implementing previews and sizes for images on web (your example React app doesn't support it) I have wrongly assumed that it is parsed by the server. It is not, it is being sent by iOS. So technically iOS, when sending image, sends three parts: original image, preview, json sizes.

Then when I have implemented sending rich content via web, I have just been sending original images and of course not getting image sizes and previews anymore. On iOS it is displayed properly, and I have updated my web implementation to assume it can be missing. Once again, bad assumption on my side.

2.  Yes I am sending this as text/plain. We are also sending custom json with mime_type `ahoy/notification` . This has more than 2KB, so it is delivered as blob to web sdk. On iOS it works just fine :) On web we have updated the code, so it also works. 

3. Already mentioned it, all works fine, sorry for the mess.

I have found now weird bug (devs will mark it as missing feature :D): iOS only accepts image/jpeg as images.

It was a suprise for us, when we have sent PNG and it was displayed properly on web platforms but not in iOS. iOS also ignores not known types (which is correct in my opinion) and so the image had never been displayed.

So my question is, does layer-web-sdk accepts rich content as base64 and not only File object?
Or maybe you know how to convert png to jpeg in javascript and deliver it as JPEG?

**Comment by michaelkantor** [comment]
Please see new docs at https://docs.layer.com/sdk/web/rich_content_guide which cover 3-part images.  I think this covers your question around base64, but to clarify: base64 may be used internally, but is no longer exposed via the WebSDK's API so that you only need to handle Blobs, and not Blobs AND base64 which may represent the same content but require different rendering.

For handling ahoy/notification, if its textual, see discussion of TextualMimeTypes at http://static.layer.com/sdk/docs-1.1/#!/api/layer.MessagePart, otherwise ignore this.

**Comment by bartoszhernas** [comment]
Ok, I tricked iOS into showing it correctly by forcing mimeType:

```javascript
const messagePart = new MessagePart(payload.file);
messagePart.mimeType = "image/jpeg";
```

All good now, thank you a lot for help!!!
I need to send you guys video what we are doing with your platform. It is really flexible and besides few issues we love it. 
We have even connected emails with Layer so our agents can reply via layer web chat to emails :P

**Comment by bartoszhernas** [comment]
Wow, haven't seen this docs earlier. Great work, will implement it tomorrow. Thanks 👍

**Comment by michaelkantor** [comment]
Would love to see videos!  And yes, the docs were released last week.

**Comment by bartoszhernas** [comment]
No way it was last week, we have updated our web sdks today to 2.0.0-beta because we needed Identity objects, so it had to be max yesterday ;). On NPM there was still 2.x version with info that it is really 1.x version. 

For others: the trick with forcing mime type doesn't work fully, the image on first loads just shows grey rectangle.

**Comment by michaelkantor** [comment]
Hey, please note the recent NPM versioning mess that forced us to rename all our versions...

1. 1.0.12 is now 1.2.1
2. 1.1 is now 2.0.2 (everything that was in 2.0.0-beta except Identity)
3. 2.0.0-beta is now 3.0.0-beta (adds Identity to 2.0.2); this may not yet be npm published, but if your staying on the beta you'll need to keep track of this to get updates to the beta.

If only NPM allowed `unpublish`...

**Comment by bartoszhernas** [comment]
Got it, we are using for now

    "layer-websdk": "2.0.0-beta.3",

as it cointains Indentities.
