### ISSUE TITLE
Safari private browsing causes issues

### ISSUE THREAD

**Issue by maximeloizeau** [layerhq/layer-websdk#105]
Hello,

In Safari, private browsing disables localstorage/indexedDB reading and writing. This leads to this error in the SDK:
`TypeError: Attempted to assign to readonly property.`

[db-manager.js:123](https://github.com/layerhq/layer-websdk/blob/2.0.0-beta.3/src/db-manager.js#L123) -> opens the database, then `request` is `null`. So the `request.onerror` throws the above error.

I added a fix for my build, where I simply test this, just after the open:
if(!request) return errorTrigger();

I didn't look if you already have a system in place to manage this sort of case, so I was not able to make a pull request.

**Reproduction steps:** try to login while in private browsing in Safari (MacOSX and iOS).
**SDK version:** 2.0.0-beta.3, and also noticed in 2.0.0-beta.1 (npm versions)

**Comment by michaelkantor** [comment]
I see it; I'll work something up, and add "Test in Private Browsing Windows" to our verification process.

**Comment by michaelkantor** [comment]
Note that there's been considerable mixup in our versioning numbers, due to an unfortunate NPM mixup.

1. 2.0.x: Contains Announcements, persistence, but no Identities (contains all the features of the former 2.0.0-beta minus Identities)
2. 3.0.0-Beta: Contains Identities (full version of what was previously the 2.0.0-beta)

I'll work on a fix for both.

**Comment by maximeloizeau** [comment]
Thank you.

Regarding the versions, do you plan to publish v3.-beta on npm ?

**Comment by michaelkantor** [comment]
Yes... once we're ready with a meaningful update, not just publishing to do a version change.

**Comment by michaelkantor** [comment]
Fixes are now in latest version of 2.0 as well as the 3.0.0-beta, and are released.
