### ISSUE TITLE
new Client() has side-effect of destroying old clients/queries

### ISSUE THREAD

**Issue by EmielM** [layerhq/layer-websdk#135]
That means that `Query.destroy`ing on old `Client`s now throw exceptions because they are already cleaned up.

This is okay for systems where lifetime is precisely managed (old query should be cleaned up before client is cleaned up), but this is often not the case in JS frameworks.

As an aside: registering Clients (and having side-effects) in its constructor function seems like a strong a anti-pattern to me. I would never expect code to behave like that.

**Comment by michaelkantor** [comment]
There is a Client Registry that allows components (and apps) to find a Client by App ID.  Having two Clients share an App ID would break many things.  This has both pros and cons.

Largest Con from my perspective is that it prevents a single app from having two clients allowing someone to authenticate as both an "Admin" user and as a regular user.

Largest Pro is that one needs only an App ID to get a Client, saving both WebSDK Components and your app from having to pass pointers to the Client everywhere. (We do have a task to investigate using some other ID, but that would mean only WebSDK components could do it, and not Apps themselves).  Its much simpler to pass an appId than a Client among Angular Components that will be inspecting that Client for changes, modifying it with tracking properties, etc....

What your calling a side effect and an anti-pattern is to my perspective is a natural part of having a registry and a standard part of working with registries in that 1. all components side effect on being created by registering themselves, and 2. components that are not distinct must either throw errors or destroy the prior component.

If you are explicitly calling `query.destroy()`, you could instead try:

```
if (!query.isDestroyed) query.destroy();
```

Alternatively, you could do:

```
if (!layer.Client.getClient(appId)) {
   client = new layer.Client({
      appId: appId
   });
}
```

One thing to keep in mind as well is that any pattern that does NOT cleanup prior Clients, means an app that iterates and recreates the Client a dozen times will now have a dozen live websocket connections... something we would consider harmful.  Alternate suggestions are welcome, but this more than anything else would have to be prevented.

**Comment by michaelkantor** [comment]
Not much folllow up here.  May at some point replace Client constructor with factory method, but thats a breaking change, and is currently the only solution that still returns a valid Client.  Reopen to discuss further.
