### ISSUE TITLE
Cache purging destroying conversations loaded without a query

### ISSUE THREAD

**Issue by rodrigopr** [layerhq/layer-websdk#137]
We're loading some conversations directly from a `Client` instance (`client.getConversation(id, load)`) and are noticing that after some time it would stop listen to events and messages list (which uses layer-react) would be cleaned.

After some debugging, we found that it was happening due to cache purging (reducing CACHE_PURGE_INTERVAL to trigger it faster).

Seems that [_checkAndPurgeCache](https://github.com/layerhq/layer-websdk/blob/master/src/client.js#L946-L953) uses [_isCachedObject](https://github.com/layerhq/layer-websdk/blob/master/src/client.js#L1000-L1007) to check if an object should be purged or not, and as we're not loading the Conversation using a Query `_isCachedObject` returns false.

**Comment by michaelkantor** [comment]
Ah... sorry for the delayed response; gmail sends most of these to my priority inbox...  Filters updated!

So, yes, this is a concern I've had, so I'll briefly discuss the rationale for this, how it works, and what can be done about it.  To be clear, while I feel like something of this sort is necessary, I'm not entirely comfortable with the side effects that you've encountered so am happy to hear ideas.

Rationale: Long lived applications can not afford to have memory just accumulate; some reasonable criteria is needed to purge cache.  For a tab open weeks or months, the memory footprint of that tab should not grow as more and more messages, conversations, etc... arrive and are cached.  Thus, a cache cleanup mechanism is needed.  

How it works: If you have a layer.Query instance, and that Query contains your message in its data, its considered to be "in-use" and therefore not available for garbage collection.  This is especially focused on cases where new Message notifications arrive for messages in Conversations your not interacting with (i.e. don't have a Query for); something that could easily accumulate over weeks of use. Its expected that almost all interactions with Layer data is via Queries.  Where does this break down?

1. New message notifications: A new message arrives on a Conversation your not currently looking at, you want to pop up a notification about that Message.  The Message gets garbage collected before the user can click on your notification... 
2. Apps that call `getMessage(id, true)`

What we've done to address this: we give a user 10 minutes to use it or lose it.  Not ideal, but for use case #1 thats typically good enough.

Solutions and work arounds:

1. https://docs.layer.com/api_reference/web-3.0/#!/api/layer.Client-static-property-CACHE_PURGE_INTERVAL is a static property you can change to any number you like.  Perhaps a week works better for you?  `layer.Client.CACHE_PURGE_INTERVAL = XXX;`
2. You could experiment with creating a Query, and then manually manipulating its `data` property (this is a bit of a hack, but if it works, insures that objects stashed here won't be garbage collected).  Make sure that the Query `model` and `dataType` are set correctly.
3. You could just use `message.toObject()` and stash a local copy of the object without any event handlers or methods.  This won't get updates/events, but preserves your data.

I'd start with #1 and only try the others if that doesn't work for you.

Michael
