### ISSUE TITLE
Crashes at startup when uglified

### ISSUE THREAD

**Issue by jeffijoe** [layerhq/layer-websdk#138]
Using UglifyJS with `drop_console`, the [following line](https://github.com/layerhq/layer-websdk/blob/master/src/logger.js#L11) fails:

```js
const supportsConsoleFormatting = Boolean(console.assert && console.assert.toString().match(/assert/));
```

with

> Cannot read property 'match' of undefined

I discovered this when building a production version of my app with Webpack.

**Comment by michaelkantor** [comment]
Ok, so as I understand it:

1. Your looking to remove all logging from your build, including logging of errors.  Are you sure you wouldn't rather override `console.log` to capture this information some other way?
2. UglifyJS has determined that `console.assert` exists, but that `console.assert.toString()` is `undefined`?  What? :-( 

Some explanation: Using console.log formatting is supported in most browsers, but not IE11/Edge.  This test is used to determine if a browser has a complete `console` implementation or not.  I could look at new tests for doing this, but you'll get much faster results fixing this on your end.

I'm open to discussion of other tests to perform to validate that a console supports formatting that would be accepted by `drop_console`.

One solution you could look at: remove `drop_console` from your uglify step, and add https://www.npmjs.com/package/grunt-remove-logging or something comparable to your build process.  Removing logging is not a difficult operation that can be performed by a better implementation than appears to be in Uglify...

**Comment by jeffijoe** [comment]
Removing `drop_console` did _"fix"_ it, I guess it's an issue with UglifyJS then?

**Comment by michaelkantor** [comment]
I'd consider that the short term fix.  There's clearly an issue with UglifyJS that our code has run afoul of.  We'll need to take a look at that, but I recommend going with the short term fix, and leave this issue open.

**Comment by vekerdyb** [comment]
+1

**Comment by michaelkantor** [comment]
Hope to ship a fix by end-of-week
