### ISSUE TITLE
Update/Get Block User list

### ISSUE THREAD

**Issue by andela-aabdulwahab** [layerhq/layer-websdk#139]
I've gone through the websdk documentation, but I can't find any available method for managing a user's block list. Is there any support for it? If no, what is the best way to achieve it with the websdk, I'm willing to put together a PR for it. Thanks.

**Comment by michaelkantor** [comment]
The WebSDK talks to Layer's Client API.  If the Client API supports something, odds are, the WebSDK does to.  Once the server team adds support for Blocking to the Client API, the WebSDK can add it.  This won't happen in the next few months.

For now, your best bet is to user Layer's Server API.  You would do this by having the browser send a request to your server, and your server would then send the block request to Layer's Server API.

**Comment by andela-aabdulwahab** [comment]
Thanks @michaelkantor.
