### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by jeffijoe** [layerhq/layer-websdk#140]
Getting the following all of a sudden:

![image](https://cloud.githubusercontent.com/assets/2505474/21773561/ddde6ed6-d68f-11e6-8c93-6c641f86d672.png)

Looks like a CORS issue, it just started happening recently.

**Comment by jeffijoe** [comment]
Just downgraded to 3.0.2, that fixes the issue. I noticed 3.1.0 uses `api-preview` rather than `api`, is that intentional?

**Comment by michaelkantor** [comment]
Hey @jeffijoe that branch was intended to connect to a preview service; its currently offline; it isn't intended for general consumption (as you can tell by the fact that the service itself is offline).

What would be helpful on my end is to understand what led you to using 3.1.0 so we can prevent these accidents in the future.  Did you get this from github digging through branches/releases?  Did you get it from NPM digging through tagged releases?  Your not the only one to hit this, and I'd appreciate any feedback on how people are getting this preview version.

**Comment by jeffijoe** [comment]
I am using `npm-check-updates` to keep my packages updated.
