### ISSUE TITLE
client.on('ready', function () {  }); sometimes  there is no automatic trigger

### ISSUE THREAD

**Issue by EasonRen** [layerhq/layer-websdk#16]
When everything is normal in local development,When I publish to the server sometimes does not trigger.

**Comment by michaelkantor** [comment]
Try 
```javascript
client.on('all', function(evtName) {console.log('EVT: ' + evtName);})
```
And see what events are Actually being triggered.  Post them back here if they don't help you.

**Comment by EasonRen** [comment]
This is normal:
  EVT: connected
  EVT: authenticated
  EVT: ready

Are not normal circumstances there is no information except for the request(GET "https://api.layer.com/messages/ffffffff-ffff-ffff-ffff-ffffffffffff")

**Comment by michaelkantor** [comment]
What is the status code and body of the error in response to GET "https://api.layer.com/messages/ffffffff-ffff-ffff-ffff-ffffffffffff"?

**Comment by EasonRen** [comment]
404 not found

**Comment by michaelkantor** [comment]
Ok, thats a correct response.  On getting that response, it should directly trigger "connected", "authenticated" and "ready". Don't see any path that would prevent that.

What browser/version/OS are you running?  
Have you tried running with a your debugger open and break-on-error enabled?

**Comment by EasonRen** [comment]
I didn't see any path which prevents that as everything is normal in local development.

Publishing environment:
OS :Windows Server 2012 R2 Standard
IIS: 8.5

The only thing I can think of is publishing environments in the United States,I was in China

**Comment by michaelkantor** [comment]
Ok, I didn't see a browser version.  Are you running this from a server instead of a browser?  If your running this from a browser, please post the browser name and browser version.

**Comment by EasonRen** [comment]
chrome49,IE11

**Comment by michaelkantor** [comment]
Ok, so chrome 49 sometimes works, and sometimes fails?
Or is it IE 11 that sometimes works and sometimes fails?
Or you observe the problem with both browsers?

One option you may want to try, is to not use the `userId` parameter when creating your Client.  This will prevent the session token from being restored.  If it doesn't try to restore the sessionToken, then it will take a different path which may work more reliably for you.  That said, I run this regularly in Chrome 48, and have never observed the problem you report.

**Comment by EasonRen** [comment]
I'll try, thank you for your answer.
