### ISSUE TITLE
Total message count from conversations list

### ISSUE THREAD

**Issue by bimusiek** [layerhq/layer-websdk#165]
Hey, I see in Network that response with all conversations contains `total_message_count` per each conversation. However, there is no way to access it from list that query returns. 

Any idea for the best way to do it?

**Comment by michaelkantor** [comment]
Thats a new field added to the server. The WebSDK will be updated to have it.

**Comment by michaelkantor** [comment]
Fix is in version 3.4.1 now available on npm and cdn.
