### ISSUE TITLE
It's impossible to remove conversation if you were removed from it.

### ISSUE THREAD

**Issue by wist543** [layerhq/layer-websdk#177]
HI. I faced with very strange issue. 
Very simple scenario:
1. create conversation with multiple users.
2. send message to it.
3. some user does replaceParticipants with same users except one (let's call him badUser).
4. every time when badUser is logged in he will see this conversation without participant (something like history mode) but he can't leave or remove it for him. I tried leave and delete(my-devices) but got 403 (with code 101 (access_denied)).

It's really simple scenario but I don't see how to remove such conversation for badUser permanently. Any ideas?) It seems like issue on server side.

**Comment by michaelkantor** [comment]
This looks to be a server bug; I'm passing this along to the server team.  Work around on client side is to not display any Conversation where participants array is empty.

**Comment by wist543** [comment]
How to check some status of this issue in the future?

**Comment by michaelkantor** [comment]
I've posted a link to this issue to our internal ticketing system.  With luck, the server engineer will post here when its fixed (however, we do not have an established process of that happening)
