### ISSUE TITLE
readStatus doesn't accurately reflect recipientStatus

### ISSUE THREAD

**Issue by jeffchheng** [layerhq/layer-websdk#178]
I'm using layer-websdk v3.3.4 and finding that `readStatus` doesn't always match `recipientStatus`.

`layerClient.getMessage('layer:///messages/8927cff7-80b9-4694-ac38-a9842850599b').readStatus;` returns `"NONE"`
`layerClient.getMessage('layer:///messages/8927cff7-80b9-4694-ac38-a9842850599b').recipientStatus;` returns:
```
{
  layer:///identities/36af24fb-89a4-4f05-b53c-89a915741871: "read",
  layer:///identities/7eb64180-86e8-4451-be7e-b0629bf62df8: "read"
}
```

I've found performing a full refresh (after marking a message as read again) will update the `readStatus`. 

Here's a screenshot from the console of another conversation and message:
![image](https://user-images.githubusercontent.com/25038173/33040583-5603a126-cdf0-11e7-9f0d-fe27cf4cad6c.png)
conversationId: `84c917e8-d78c-419a-bfeb-9dde24a8dfdc`
messageId: `layer:///messages/aa320ad6-ab76-47a9-a01c-a235b4a53a28`

**Comment by michaelkantor** [comment]
Can you check for `layerClient.participants`?  If that is an empty array then its probably not going to calculate this correctly as it has no way of knowing who all is in the Conversation and if all of them have read it or not.  That part at least is a limitation of the server; handling that by returning `NONE` is probably less than ideal; returning simply an empty string might be less bizarre.

**Comment by jeffchheng** [comment]
It's an array, and the `id`s match the ones in the `recipientStatus` I linked above.

**Comment by michaelkantor** [comment]
Ok.  Can you tell if the Message is loading before or after the Conversation?

Does calling `message.__updateRecipientStatus(message.recipientStatus, {})` cause the `readStatus` to change?

**Comment by jeffchheng** [comment]
Yep, doing that updated it from `NONE` to `SOME`.

**Comment by benhorst** [comment]
@michaelkantor this typically happens when the local user sends the message. Hoping maybe repro steps help.

I'm in a Conversation with you and jeff. I'm signed in, have an initialized layerClient, and have the conversation loaded.
I send a Message.
That last message is the one that has improper `readStatus`. The `isUnread`/`isRead` and `recipientStatus`updates properly when you or Jeff read it, but the message's `readStatus` is still 'NONE'.

**Comment by michaelkantor** [comment]
I'm sorry Jeff; I don't really understand the state needed to have that evaluate to `NONE` right now...  except perhaps if the Conversation object has not yet loaded at the time the calculation is being made.  If the sequencing for your app isn't allowing this feature to work, I recommend just directly working with the `recipientStatus` property.  I'll see if I can suppress any values, and force this to reevaluate after the Conversation loads (if it hasn't already loaded).  But that fix won't be coming soon.

**Comment by benhorst** [comment]
We had some trouble getting the proper repo at the end of last week (then all went away for holidays). We removed the code that depended on readStatus (we didn't really need it in addition to isRead/isUnread). If we have a significant problem with a steady repro we will bring it back up with the team. Thanks!

**Comment by michaelkantor** [comment]
Sounds good; we have a Jira ticket to look more closely at this. But if nobody is currently having a problem, I'm going to update this ticket to closed.
