### ISSUE TITLE
Not receiving messages back

### ISSUE THREAD

**Issue by ericlewis** [layerhq/layer-websdk#180]
I have a conversation where I am sending a message and get a reply back from the server. But I can't see a response until I have refreshed.

**Comment by ericlewis** [comment]
update: tried different account, and it works fine. it appears my account was blacklisted or something fo sending too many messages?

**Comment by michaelkantor** [comment]
Honestly, I could speculate but it would be such complete guesswork that the odds of my guessing correctly is too small to justify the effort :-)  

I'm going to close the ticket since it appears to not be blocking you further; reopen if this occurs again.

**Comment by ericlewis** [comment]
fair enough! we are going to talk directly to layer soon.
