### ISSUE TITLE
Updating a message via REST does not trigger change event in query

### ISSUE THREAD

**Issue by jperezApplause** [layerhq/layer-websdk#181]
websdk **v3.4.0**

Not sure if this is the right place to report this issue, but when I edit a message via REST the message is successfully updated, but there is no change event triggered in the message query.

I've tried both endpoints for updating message parts to see if it made a difference: 
[Replace all parts](https://docs.layer.com/reference/client_api/messages.out#replace-all-message-parts)
[Update message part](https://docs.layer.com/reference/client_api/messages.out#replace-all-message-parts)

neither triggered the event. The query is otherwise fine.

**Comment by michaelkantor** [comment]
Looking into this.  Might not get back until Monday.

**Comment by michaelkantor** [comment]
Hey, this feature, while available on the server now, it should not have been published to our docs because its not yet supported by clients.  Expect support to role out in Q1 of next year.  You'll need to work around lack of Message Editing features until then.
