### ISSUE TITLE
In some occasions chat msg is skipped 

### ISSUE THREAD

**Issue by adylevy** [layerhq/layer-websdk#183]
We are getting complains from users that while chatting with their friends there are msgs that not being delivered. 
Since we are listening to the 'create msg' hook we know that the msg was sent but never received.
only after the user is loading the app again (which in turn creates a new client, fetches all the msgs again) the msg is shown.

Can you delve into it?

**Comment by michaelkantor** [comment]
Please see http://status.layer.com/incidents/21g3gfgw6m4h
