### ISSUE TITLE
delete conversation for current user 

### ISSUE THREAD

**Issue by grimabe** [layerhq/layer-websdk#19]
Hi saw in the online documentation that deleting a conversation is implemented but it will delete the conversation for the others participants as well.

Do you have an idea when the option to delete only for the current participant will be available ?

Thanks

**Comment by michaelkantor** [comment]
We are awaiting support for this from our server.  My understanding is that this support is close to being available.  That said, we are also working towards a GA release of the Web SDK, and may add support for that feature in an update rather than as part of GA.

**Comment by grimabe** [comment]
Thank you for your answer.
Is there a roadmap available somewhere ?

**Comment by michaelkantor** [comment]
There are two types of roadmaps, neither is currently public:
1. The roadmap for what our servers/services will provide.  For more information on this, you might get a better answer via http://slack.layer.com
2. The roadmap for what the WebSDK itself and its spinoff projects (such as a UI framework) will provide.  
We'll be fleshing that out once this goes GA.  For now, things high in the list are:

* Adding support for any of the missing services that the server provides; including delete for current participant, announcements, Querying, etc.
* Improved offline support via IndexedDB
* A UI Framework

None of these represent small investments of effort, but we hope to have clearer priorities and sequencing of these by GA.  Feel free to register with our slack account and chime in with feature requests... requests made there will get the attention of more people than just our javascript team.

**Comment by grimabe** [comment]
Thank you for this detailed answer
