### ISSUE TITLE
there is any prepared chat for websdk?

### ISSUE THREAD

**Issue by rockatansky** [layerhq/layer-websdk#20]
If i want use the websdk i have a complete chat with all graphical things like the iOS and Android SDKs?

The method ```renderMyUI``` is effectively not defined...

Bests
Rocky

**Comment by michaelkantor** [comment]
The WebSDK is a framework for integrating YOUR user interface with OUR servers and services.  It comes with bells and whistles like being able to tolerate periods of being offline.  But it is not itself a UI framework such Atlas which ships with our IOS and Android SDKs.

In any example you see from us, if the word "My" shows up in a function name, its intended to imply that its a function that *you* provide; its implicitly not defined, as the details of HOW its implemented will depend upon what UI framework you are building with.

If your looking for an easier starting point for building a UI, please see our https://github.com/layerhq/layer-js-sampleapps repository.
