### ISSUE TITLE
Query for metadata

### ISSUE THREAD

**Issue by alanhoff** [layerhq/layer-websdk#56]
Is it possible for the WebSDK to create queries based on conversation's metada?

```javascript
metadata: {
  assigned: ['admin1', 'admin2']
}
```

I'm trying to return only conversations that have the current user_id in `metadata.assigned` array.

**Comment by michaelkantor** [comment]
Such capabilities are planned, but not available at this time.  For this to work well, it needs to be implemented on the server side, and that work is still ahead of us.

**Comment by alanhoff** [comment]
@michaelkantor that's for metadata in general? Can't I query for that even using the client rest interface?

**Comment by michaelkantor** [comment]
All Querying capabilities are on our roadmap, but not available at this time.  At this point, the best you can do is hit our REST API and page through lists, and filter the results on your server.

One thing you can do if you want the ability to run queries Now (i.e. not wait for us to build it) is to look at either:

* [Webhooks](developer.layer.com/docs/webhooks): You can use these to build and maintain in real time your own queryable database
* [Data Export](https://developer.layer.com/docs/platform/data): You can get a daily update to your data and update your own queryable database

Using either of these, you can manage any "Admin" queries from your own server without any limitations on what you can query for, or how/when the queries are issued.  As I don't know when we will roll our Querying, you may not only want to look into this approach, but also may find it more flexible than anything we roll out in the future.

**Comment by alanhoff** [comment]
Ok got it, thx for the answer.
