### ISSUE TITLE
Strange behaviour while querying in v1.0.6

### ISSUE THREAD

**Issue by alanhoff** [layerhq/layer-websdk#62]
Hello there! I was using a simple logic for loading messages and displaying a loading gif while while the webSDK was busy fetching/updating a message query:

```javascript
// Show loading gif
activateOverlay()

// Keep watching for messages
let query = client.createQuery({
  model: layer.Query.Message,
  predicate: `conversation.id = '${conversation.id}'`
})

// Deactivate overlay when first received
query.once('change', () => {
  deactivateOverlay()
})

// keep messages update
query.on('change', () => {
  handleChanges()
})
``` 

But due to [recent changes](https://github.com/layerhq/layer-websdk/blob/f65a3135ba981e38bc04dbe219a82deb9c1ab65a/src/query.js#L482-L514) a new conversation with no messages will keep calling `this._retryCount` until `Query.MaxRetryCount` is reached, that's because the condition `else if (this.size === 0)` will always evaluate to true since the conversation have no messages at all. The result is that the loading gif stays in the screen until `Query.MaxRetryCount`.

Am I using a wrong logic for v1.0.6?

**Comment by michaelkantor** [comment]
That change is a hack that won't make it to version 1.1.0 designed to account for the fact that sometimes it takes a few seconds for the server to "catch up" with messages for a new Conversation.

As you noted, it defines a static variable MaxRetryCount:
https://github.com/layerhq/layer-websdk/blob/master/src/query.js#L1210

You might consider adding the following code during initialization:

```
layer.Query.MaxRetryCount = 0;
```

I have not tested this solution...  but it looks right, and this variable is intended to let you customize it.

**Comment by alanhoff** [comment]
That worked very well, thanks once again!
