### ISSUE TITLE
evt.callback error

### ISSUE THREAD

**Issue by EasonRen** [layerhq/layer-websdk#8]
`var layer = require('layer-websdk');
var config = require('./config.json');
var request = require('request');`

`var client = new layer.Client({
    appId: config.LayerAppID,
    userId: config.UserID
});`

`function getIdentityToken(layerNonce, callback) {
    
    var option = {
        url: config.IdentityTokenUrl,
        method: "POST",
        json: true,
        headers: {
            "Content-Type": 'application/json',
        },
        body: { data: { nonce: layerNonce } }
    };

    request(option, function (error, response, body) {
        if (!error && response.statusCode == 200) {
            callback(body.identity_token);
        }
    });
} `

`client.on('challenge',` function (evt) {

    getIdentityToken(evt.nonce, function (identityToken) {
        evt.callback(identityToken);
    });
});`

The last error is "Layer-Error: 105 (invalid_property): Nonce not found or expired.",I  can be sure of is that I can get "body.identity_token".

**Comment by michaelkantor** [comment]
1. My understanding of your issue is that your firing a request to the Identity Provider and getting back this error.  Can you verify that?  
2. I can not tell from your code whether you have your own identity server or are using our sample identity server.  If its our sample identity provider, please paste the URL you used here.
3. One thing you might try, just in case:

```javascript
var option = {
    url: config.IdentityTokenUrl,
    method: "POST",
    json: true,
    headers: {
        "Content-Type": 'application/json',
    },
    body: {nonce: layerNonce } // Removed "data"
};
```

**Comment by EasonRen** [comment]
@michaelkantor thank you

**Comment by nha** [comment]
How does the IdentityTokenUrl look ?
I have a sample token in the dashboard ( /integrations , platform api, sample token). But I don't see the url ?

**Comment by michaelkantor** [comment]
If you using the sample apps at https://github.com/layerhq/layer-js-sampleapps:

That app is setup to use Layer's Sample Identity Services, which calls the Identity Service as follows:

https://github.com/layerhq/layer-js-sampleapps/blob/master/common/layerSample.js#L27-L40

If your providing your own Identity Service, then the URL looks like whatever you have designed your server to accept.  For more info on providing your own Identity Service:  https://developer.layer.com/docs/websdk/guides#authentication

**Comment by nha** [comment]
The sample app works perfectly, thanks.
