### ISSUE TITLE
evt.callback  GET https://api.layer.com/messages/ffffffff-ffff-ffff-ffff-ffffffffffff

### ISSUE THREAD

**Issue by nha** [layerhq/layer-websdk#9]
In the following code, I am passing an identity token taken from the server : 

        client.on('challenge', function(evt) {
            getIdentityToken(evt.nonce, function(err, identityToken) {
                evt.callback(identityToken);
            });
        });

A GET request to ` https://api.layer.com/messages/ffffffff-ffff-ffff-ffff-ffffffffffff` is made instead.

(Screenshot : https://infinit.io/_/34TjWbc )

The `ready` event is fired though, I don't know yet if this is a problem for using the driver.

**Comment by michaelkantor** [comment]
The request to https://api.layer.com/messages/ffffffff-ffff-ffff-ffff-ffffffffffff is a hack; improving upon that is in our backlog.  Its role is:

1. If you initialize the Client with a userId, the client will check to see if its cached a session token for that user
2. If it has, it attempts to validate that the session-token is still valid with a quick and light weight request
3. Either the request for Message fffffff.... will come back with an authentication error (session token is invalid) or it will come back with a "not found" error (or perhaps an actual message if we want to bet on a long shot).  

If its any response other than an authentication error, then the cached session token is still good, and the "ready" event then fires.  If it IS an auth error, then this is an old session token, and we go through the challenge.

There is a request on file for the server team to add a nicer way than Message-fffffff to validate a token.  Until they get to it, this should be considered expected and correct behavior.
