### ISSUE TITLE
How can I determine when all of a Conversation's messages have been fetched?

### ISSUE THREAD

**Issue by yangmillstheory** [layerhq/layer-websdk#90]

**Comment by michaelkantor** [comment]
Yeah, recently fixed this in the WebSDK 2.0 Beta, but the current release does not nicely handle this.

Best bet is to compare how many results you requested and compare it with how many you got back.  If you ever page back and get 0 results, then you've definitely reached the end.  But if you request an increase in paginationWindow of 50 and got back 40, then that also means you've reached the end.

This will be better in 2.0.

Michael

**Comment by yangmillstheory** [comment]
Yep.

By the way, this looks like it would work for an iOS client: https://developer.layer.com/docs/ios/api#lyrconversation.

The use case is paginating:

- show loading message when scrolling up and a new page is being fetched
- show "this is the start of your conversation" when no more pages exist

We programmatically detect when pages exist by storing the current page and the number of messages received in the Redux store. Then Components use this helper function in lifecycle hooks (parameters would come from `props`):

```
import { isEmpty } from 'lodash'
import { MESSAGE_PAGE_LENGTH } from './constants'

export default function didFinishPagingMessages(paginationWindow, messages) {
  return !isEmpty(messages) && paginationWindow > messages.length + MESSAGE_PAGE_LENGTH
}
```

**Comment by michaelkantor** [comment]
Note that paginationWindow is a bit of a fluid concept; what you really need is the delta.

If I do `query.update({paginationWindow: query.paginationWindow + 50})` repeatedly, I will get a paginationWindow that has no basis on actual message counts.  Think of paginationWindow as a "requested page size" rather than an actual page size.
