### ISSUE TITLE
Online presence

### ISSUE THREAD

**Issue by blackxored** [layerhq/layer-websdk#91]
How to check for online presence, for example, to display user online indicators? I know Firebase and PubNub have this.

**Comment by michaelkantor** [comment]
This is on our server team's roadmap, but is not expected in the next few months.  Once its available on the server, adding it to the WebSDK will be a high priority.  Until then, depending on the scale you need, presence alone might be a lightweight service that can be done using something socketio, or a feature you can hold off on until we release it.

**Comment by michaelkantor** [comment]
Closing issue; its a high priority in our roadmap, and has no further actions needed in this thread.  But not a bug that needs fixing.
