### ISSUE TITLE
Is there any way to mark a message as unread after it's read?

### ISSUE THREAD

**Issue by yangmillstheory** [layerhq/layer-websdk#94]
The example [here](http://static.layer.com/sdk/docs/#!/api/layer.Message-property-isRead) marks the message as read.

I've been trying to mark read messages as unread programmatically, but it doesn't seem to work. Given how seamless it is to mark a message as read, I'm wondering if this is even possible?

**Comment by maximeloizeau** [comment]
From the source code, it doesn't seem possible right now: https://github.com/layerhq/layer-websdk/blob/98be98c9142a484f67f063281b698f33adb337fc/src/message.js#L416

And if you look at the REST API, you can only send read/delivery state as a receipt (and since the sdk is using the API).

**Comment by michaelkantor** [comment]
The server does not support marking a Message as unread.  That's not going to change in the foreseeable future.

**Comment by yangmillstheory** [comment]
Thanks @michaelkantor for the authoritative response.
